-- MySQL Script generated by MySQL Workbench
-- Wed Oct 21 23:19:52 2015
-- Model: Server DB Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema greatRoom
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `greatRoom` ;

-- -----------------------------------------------------
-- Schema greatRoom
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `greatRoom` DEFAULT CHARACTER SET utf8 ;
USE `greatRoom` ;

-- -----------------------------------------------------
-- Table `greatRoom`.`group`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greatRoom`.`group` ;

CREATE TABLE IF NOT EXISTS `greatRoom`.`group` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(255) NULL,
  `description` VARCHAR(255) NULL,
  `image_url` VARCHAR(150) NULL,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greatRoom`.`location`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greatRoom`.`location` ;

CREATE TABLE IF NOT EXISTS `greatRoom`.`location` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `type` ENUM('GPS', 'IBEACON') NOT NULL,
  `group_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_location_place_idx` (`group_id` ASC),
  CONSTRAINT `fk_location_place`
    FOREIGN KEY (`group_id`)
    REFERENCES `greatRoom`.`group` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greatRoom`.`location_gps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greatRoom`.`location_gps` ;

CREATE TABLE IF NOT EXISTS `greatRoom`.`location_gps` (
  `latitude` DOUBLE NOT NULL,
  `longitude` DOUBLE NOT NULL,
  `range` DOUBLE NULL,
  `location_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`location_id`),
  CONSTRAINT `fk_location_gps_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `greatRoom`.`location` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greatRoom`.`location_ibeacon`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greatRoom`.`location_ibeacon` ;

CREATE TABLE IF NOT EXISTS `greatRoom`.`location_ibeacon` (
  `uuid` VARCHAR(255) NOT NULL,
  `location_id` INT UNSIGNED NOT NULL,
  PRIMARY KEY (`location_id`),
  CONSTRAINT `fk_location_ibeacon_location1`
    FOREIGN KEY (`location_id`)
    REFERENCES `greatRoom`.`location` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greatRoom`.`object`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greatRoom`.`object` ;

CREATE TABLE IF NOT EXISTS `greatRoom`.`object` (
  `id` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `uuid` VARCHAR(255) NULL,
  `type` ENUM('PERSON') NOT NULL,
  `creation_date` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `uuid_UNIQUE` (`uuid` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greatRoom`.`person`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greatRoom`.`person` ;

CREATE TABLE IF NOT EXISTS `greatRoom`.`person` (
  `object_id` INT UNSIGNED NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `name` VARCHAR(255) NULL,
  `image_url` VARCHAR(255) NULL,
  PRIMARY KEY (`object_id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  CONSTRAINT `fk_person_object1`
    FOREIGN KEY (`object_id`)
    REFERENCES `greatRoom`.`object` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `greatRoom`.`group_chekin`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `greatRoom`.`group_chekin` ;

CREATE TABLE IF NOT EXISTS `greatRoom`.`group_chekin` (
  `group_id` INT UNSIGNED NOT NULL,
  `object_id` INT UNSIGNED NOT NULL,
  `date` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  INDEX `fk_group_has_object_object1_idx` (`object_id` ASC),
  INDEX `fk_group_has_object_group1_idx` (`group_id` ASC),
  CONSTRAINT `fk_group_has_object_group1`
    FOREIGN KEY (`group_id`)
    REFERENCES `greatRoom`.`group` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_group_has_object_object1`
    FOREIGN KEY (`object_id`)
    REFERENCES `greatRoom`.`object` (`id`)
    ON DELETE CASCADE
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
